### ISSUE TITLE
AD user emails do not appear to be updated when chaged in WA

### ISSUE THREAD

**Issue by ctops1** [pumpingstationone/WA2AD#8] opened 2019-03-31 22:28 UTC
Example:

for user superchomp, email was stuck on an old email, despite email having been updated in WA. I manually updated the user's email in AD for now

**Comment by tachoknight** [comment] 2019-04-01 14:57
Hm, hadn't considered this particular use case. The issue is in `private void UpdateUser(Member member, ref UserPrincipal userPrincipal)` in that it doesn't check for a different email for the user. Easy fix (can't do it right now but will tonight). 

Can you think of any other thing that might be updated in WA that would need to be replicated down to AD?

**Comment by tachoknight** [comment] 2019-04-13 23:56
Fixed in 8e49b64cd9bcafff0dda909d2d5e08884dbca2be

**Comment by tachoknight** [comment] 2019-04-13 23:58
@ctops1 If you check Testy McTestface in WA, I updated the email address to now have a few "z" at the beginning, and that is now set as the userPrincipalName in AD.

**Closed as completed** 2019-08-14 21:45 UTC
Labels: bug
